# Generated by Django 4.1.5 on 2023-01-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=150)),
                (
                    "description",
                    models.CharField(
                        default="", help_text="News content", max_length=5000
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, blank=True, unique=True)),
            ],
            options={
                "verbose_name_plural": "📰 News",
            },
        ),
    ]
