# Generated by Django 4.1.5 on 2023-01-28 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="comments",
            name="language",
            field=models.CharField(
                choices=[("en", "En"), ("de", "De"), ("fr", "Fr")],
                default="en",
                max_length=2,
            ),
        ),
    ]
